### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by Chayapol-c**
# Description
Add authentication to project

## Change
- authentication using jwt bearer token.
- hashing user's password.
- add dependencies to [`requirements.txt`](https://github.com/OGYH-Team/ogyh-backend/blob/feature/authentication/requirements.txt).

## Checklist
- [x] All test passes?
- [x] Requires dependency update?
- [x] Open API easy to read?
- [x] No bugs and errors when running?
- [x] Is docstring easy to read?

### CODE REVIEW

**Comment by Kuea666** [comment]
excellent

**Comment by Kuea666** [comment]
excellent

**Review by Kuea666 — APPROVED** [review]
excellent

**Comment by ttxking** [comment]
Is 307 response fixed for the skip in test_authentication? If it's already been fixed, you can remove the skip

**Pull request merged**
